<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('shop')->group(function () {
    // 首页
    Route::get('', [\App\Api\Shop\Controllers\IndexController::class, 'index']);
});
// end
